### ISSUE TITLE
Check code for remaining todos or commented out code

### ISSUE THREAD

**Issue by hydrogenoxide** [nicokn/analyzer#12]
https://github.com/goblint/analyzer/pull/260/files#r662065053
https://github.com/goblint/analyzer/pull/260/files#r662066966
https://github.com/goblint/analyzer/pull/260/files#r662099461
https://github.com/goblint/analyzer/pull/260/files#r662098922
https://github.com/goblint/analyzer/pull/260/files#r662119384
https://github.com/goblint/analyzer/pull/260/files#r662136452

**Comment by MartinWehking** [comment]
Most TODOs + dead code + commented out code should be removed now

**Comment by felihong** [comment]
Double-checked all commented out etc., it should be already removed now.
