### ISSUE TITLE
Simplify checking for bottom

### ISSUE THREAD

**Issue by hydrogenoxide** [nicokn/analyzer#14]
https://github.com/goblint/analyzer/pull/260/files#r662098220 Many
functions have the same matching pattern that checks if one or both of
the operands are bottom. This should be put in a separate function.

**Comment by nicokn** [comment]
What is the purpose of the `is_bot` function? Could it be used?

**Comment by nicokn** [comment]
or maybe something like this?

```ocaml 
let arith2 f ik x y = match x, y with
    | None, None -> bot_of ik
    | None, _ | _, None -> raise (ArithmeticOnIntegerBot (Printf.sprintf "%s op %s" (show x) (show y)))
    | Some (c1, m1), Some (c2, m2) -> f ik x y 
```
