### ISSUE TITLE
Check if `include Std(...)` in congruence is really necessary

### ISSUE THREAD

**Issue by hydrogenoxide** [nicokn/analyzer#2]

**Comment by nicokn** [comment]
Std(...) includes the following functions: `pretty`, `is_bot`, `is_top_of`, `of_interval`, `to_incl_list`, `is_excl_list`, `of_excl_list`, `to_excl_list`, `tag`, `invariant`, `printXml`, `pretty_diff`, `compare`, `hash`

**Comment by nicokn** [comment]
We should move the include statement above the implementations of `is_top` etc. to avoid overriding
