### ISSUE TITLE
Move some functions closer to/inside the functions where they are needed

### ISSUE THREAD

**Issue by hydrogenoxide** [nicokn/analyzer#25]
https://github.com/goblint/analyzer/pull/260/files#r662092880 E.g.,
`of_pair` is only used in `arbitrary`. Such functions should be moved
inside the only function where they are used.

**Comment by MartinWehking** [comment]
I've moved `of_pair` into `arbitrary`, `congruence_series` into `meet `and `is_prime` into `shift_left`

**Comment by MartinWehking** [comment]
(Reopened so we are reminded that there might be more possibly movable functions )
