### ISSUE TITLE
Set refine with own domain to meet

### ISSUE THREAD

**Issue by hydrogenoxide** [nicokn/analyzer#9]
https://github.com/goblint/analyzer/pull/260/files#r662054441

**Comment by MartinWehking** [comment]
Should be done.
Just to summarize, I've added meet refinements for the following domains:
Interval
Congruence
Enums (Exc and Exc, Incl and Incl, Incl meet Excl was already implemented (see issue #7 )
DefExc (Excluded and Excluded)
